SSound-Music-Main/SSoundMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from SSoundMusic.views import HomeView 
from SSoundMusic.views import UserCreateView, UserCreateDoneTV 

from django.conf.urls.static import static #photo 앱 추가 
from django.conf import settings #photo 앱 추가


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('photo/',include('photo.urls', namespace='photo')), #photo 앱 추가 
    path('streaming/',include('streaming.urls',namespace="streaming")), #스트리밍앱 추가 

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) #추가 

SSound-Music-Main/photo/urls.py
from django.conf.urls import url
from django.urls import path
from photo.views import * 

app_name = "photo"

urlpatterns = [
    
    path('', AlbumLV.as_view(), name='index'),
    path('album/', AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>', AlbumDV.as_view(),name='album_detail'),
    path('photo/<int:pk>', PhotoDV.as_view(), name='photo_detail'),


]

SSound-Music-Main/streaming/urls.py
from django.contrib import admin 
from django.urls import path 
from streaming.views import *

app_name="streaming"

urlpatterns = [ 
    path('',MusicMain.as_view(),name="index"),
    path('play',MusicStreaming.as_view(),name='play'),
    path('search',SearchFormView.as_view(),name="search"),
   

]

SSound-Music-Main/photo/models.py
from django.db import models

# Create your models here.
# from __future__ import unicode_literals 
from django.utils.encoding import python_2_unicode_compatible
from django.db import models 
from django.urls import reverse 
from photo.fields import ThumbnailImageField #사진에 대한 원본 이미지와 썸네일 이미지 모두 저장 



@python_2_unicode_compatible
class Album(models.Model): 
    name = models.CharField(max_length=50)
    description = models.CharField('Several Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name 

    def get_absolute_url(self): 
        return reverse('photo:album_detail',args=(self.id,))
        
@python_2_unicode_compatible

class Photo(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('photo Description',blank=True)
    upload_date = models.DateTimeField('Upload Date',auto_now_add=True)

    class Meta: 
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self): 
        return reverse('photo:photo_detail',args=(self.id,))

SSound-Music-Main/streaming/models.py
from django.db import models
from django.contrib.auth.models import User #login/ logout 
# Create your models here.

class Music(models.Model):
    music_number = models.IntegerField()
    artist = models.ForeignKey('Artist', on_delete=models.CASCADE) # fk 지정방법? 
    album = models.IntegerField()
    title = models.CharField(max_length=30)
    genre = models.IntegerField() 
    Release_Date = models.DateField(auto_now=False,auto_now_add=True) 
    songwriting = models.CharField('작사가',max_length=30)  
    composer = models.CharField('작곡가',max_length=30)      
    music_arranger = models.CharField('편곡가',max_length=30) 
    music_length = models.IntegerField()
    sound_quality = models.CharField(max_length=10)  # charField 인가 Int인가 
    music_images_url = models.CharField('이미지 경로',max_length=30)
    video_path = models.CharField('파일 경로',max_length=40) # 테스트용으로 체크 
    total_streaming = models.IntegerField('총 재생수')
    music_price = models.IntegerField('음원가격')
    total_profit = models.IntegerField('총 음원수익')
    entainment = models.CharField('기획사',max_length=30)
    hashe = models.CharField('해쉬값',max_length=100) 

    def __str__(self): 
        return self.title


class Artist(models.Model):
    email = models.EmailField(max_length=254)
    user_password = models.CharField('패스워드',max_length=40)
    authority_code = models.IntegerField("권한부여코드")
    nickname = models.CharField("닉네임",max_length=30)
    profile_url = models.CharField('이미지 경로',max_length=50)
    own_coin = models.IntegerField('소유하고 있는 코인')
    country_code = models.IntegerField('국적코드')

    def __str__(self): 
        return self.email

class Company(models.Model):
    email = models.ForeignKey('Artist',on_delete=models.CASCADE)
    company = models.IntegerField()  #pk 설정 
    company_name = models.IntegerField()
    compnay_representation = models.IntegerField() 

class Code(models.Model): 
    group_code = models.IntegerField()
    more_code = models.IntegerField()
    code_label = models.IntegerField() # 코드레이블 아직 파악 못함. 

SSound-Music-Main/streaming/forms.py
from django import forms 

class MusicSearchForm(forms.Form): 
    search_word = forms.CharField(label='Search Word')

    

SSound-Music-Main/SSoundMusic/views.py
from django.views.generic.base import TemplateView

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class HomeView(TemplateView):
    template_name = "home.html"

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

SSound-Music-Main/photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView 
from photo.models import Album,Photo 
# Create your views here.

class AlbumLV(ListView): 
    model = Album
    template_name = 'album_list.html' 

class AlbumDV(DetailView): 
    model = Album
    template_name = 'album_detail.html'

class PhotoDV(DetailView): 
    model = Photo 
    template_name = 'photo_detail.html'
    

SSound-Music-Main/streaming/views.py
from django.views.generic import ListView,DetailView,TemplateView 
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView 
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.views.generic import FormView #클래스형 제네릭뷰
# Create your views here.
from django.views.generic.edit import FormView
from streaming.forms import MusicSearchForm
from django.db.models import Q 
from django.shortcuts import render #단축함수 render  

class SearchFormView(FormView): 
    form_class = MusicSearchForm 
    template_name = 'streaming/streaming_search.html'

    def form_vaild(self,form): 
        schWord = '%s' % self.request.POST['search_word']
        music_list = Music.objects.filter(Q(title__icontains=schWord) | Q(artist__icontains=schWord) | Q(album__icontains=schWord) 
                    | Q(genre__icontains=schWord)).distinct() 

        context = {}
        context['form'] = form 
        context['search_term'] = schWord 
        context['object_list'] = music_list 

        return render(self.request, self.template_name, render) 

class MusicStreaming(TemplateView):
    template_name='streaming/streaming_play.html'

class MusicMain(TemplateView): 
    template_name='streaming/streaming.html'

SSound-Music-Main/photo/templates/album_detail.html
{% block title %}  {% endblock %}

{% load staticfiles %}
<link rel="stylesheet" href="../../static/css/photo.css">


{% block content %}
<div id="content">
    <h2 style="display:inline">{{object.name}}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>

    <hr/>

    <div class="album-detail">
        {% for photo in object.photo_set.all %}
        <div class="album-detail-photo">
            <a href="{{photo.get_absoulte_url">
                <img class="thumbnail" src="{{ photo.image.thumb_url }}" /> 
            </a>
            <li>{{ photo.title }}</li>
            <li>{{ photo.upload_date |date:"Y-m-d"}}</li>
        </div>
            {% endfor %}
    </div>

</div>
{% endblock %}1

SSound-Music-Main/photo/templates/album_list.html
{% block title %}  {% endblock %}

{% load staticfiles %} 
<link rel="stylesheet" href="../../static/css/photo.css">

{% block content %}
<div id="content">
    {% for item in object_list %}
        <div class="clear_float"> 
            <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id%}"> 
            {{ item.name }}</a></h2> 
            &emsp;<b><i>{{ item.description }}</i></b> 
        </div>

    <hr/> 

    <div class="album-list">
        {% for photo in item.photo_set.all|slice:":5" %}
        <div class="album-list-photo">
            <a href="{{ photo.get_absolute_url }}">
            <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
            </a>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        </div>
    
    {% endblock %}

SSound-Music-Main/photo/templates/photo_detail.html
{% block title %}album_list.html{% endblock %}

{% load staticfiles %} 
<link rel="stylesheet" href="../../static/css/photo.css">

{% block content %}
<div id="content">
    <h2>{{ object.title }} </h2>
</div>

<table class="photo-detail">
    <tr>
        <td>
            <a href="{{ object.image.url }}">
            <img style="max-width:100%" src="{{ object.image.url }}" />
            </a>
        </td>

        <td>
            <ul>
                <li>Photo Description</li>
                {% if object.description %}<p>{{ object.description | linebreaks }}</p>
                {% else %}<p>(blank></p> {% endif %}
                <li>Album name</li>
                <p><a href="{% url 'photo:album_detail' object.album.id %}">
                {{ object.album.name }}    
                </a></p> 
                
            </ul>
        </td>
    </tr>
</table>

</div>
{% endblock %}
    
    

SSound-Music-Main/streaming/templates/streaming/streaming.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    
</head>
<body>
    <div id=app>
        {% load static %}

        <!-- <srcipt scr="{% static 'js/sing-app/app.3a227d38.js'%}"></srcipt>
        <srcipt scr="{% static 'js/sing-app/chunk-vendors.32c634c1.js'%}"></srcipt>
        <script src="{% static 'css/app.70347e42.css'%}"></script>
        <script src="{% static 'css/chunk-vendors.a8ed7332.css'%}"></script> -->
        <!-- <script src="{% static 'js/trello/build.js'%}"></script> -->

        <!-- <script src="{% static 'js/todo/build.js'%}"></script>  -->        
        <!-- <srcipt scr="{% static 'js/soundcloud/js/app.0c83980c46d419978a63.js'%}"></srcipt>
        <srcipt scr="{% static 'js/soundcloud/js/manifest.2ae2e69a05c33dfc65f8.js'%}"></srcipt>
        <srcipt scr="{% static 'js/soundcloud/js/vendor.aebcd74ca64ea5057676.js'%}"></srcipt>
        <srcipt scr="{% static 'js/soundclo1ud/css/app.01242e30cbf22bd08db7a6435e3de8c6.css'%}"></srcipt> -->

        <!-- theme -->
        <script src="{% static 'js/theme/build.js'%}"></script>

    </div>

    <div>
        검색
    </div>

</body>
</html>

SSound-Music-Main/streaming/templates/streaming/streaming_play.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>4-single-file-component</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <div>
    
    </div>

    <div class="heading">
        {% load static %}
        <img src="{% static 'images/logo.png'%}" width="5%" height="5%">
    </div>
    
    <div id="app"></div>
    {% load static %}
    <script src="{% static 'js/streaming/build.js'%}"></script>
</body>
</html>

SSound-Music-Main/streaming/templates/streaming/streaming_search.html
{% block title %} music_search_html {% endblock %} 

{% block content %}
<div id="content"> 

    <h1>Music Search</h1>

<form action="." method="post"> {% csrf token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" />

</form>

<br/><br/>
{ % if object_list % }
{ % for music in object_list % }
    <h2><a href="{{ music.get_absolute_url }}">{{music.title}}</a></h2>
        {{music.modify_date | date:"N d, Y"}}
        
{% endfor %}
<!-- 
{% for artist in object_list %}
<h2><a href=""></a></h2> -->

{% elif search_term %}
<b><i>Search Word({{ search_term }}) Not Found ! </i></b>
{% endif %}

</div>
{% endblock %}

SSound-Music-Main/templates/base.html
<!-- <div id="header">
    <h2 class="maintitle">Easy&amp;디장고</h2>

    {% if user.is_active %}
    <h4 class="welcome">Welcome,
        <strong>{% firstof user.get_short_name user.get_username %}</strong>
        <a href="{% url 'password_change' %}">Change Password</a>
        <a href="{% url 'logout' %}">Logout</a>

        </h4>
        {% else %}
    <h4 class="welcome">Welcome,anoy 
        <a href="{% url 'login'%}">Login</a>
        <a href="{% url 'register'%}">Register</a>

        </h4>
        {% endif %}

</div>  


<li><a href="{% url 'streaming:search' %}">Search</a></li>
<li><a href="{% url 'admin:index' %}">Admin</a></li>


<div id="menu">

<li><a href="{% url 'photo:index' %}"></li>

</div> -->